INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (1,'Jeronima','Alberca Diaz',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (2,'Coral','Almansa Dominguez',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (3,'Fco Javier','Benitez del Pozo',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (4,'Sergio','Carranza Leon',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (5,'Juan Antonio','Cubero Lopez',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (6,'Pablo','Duran Camacho',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (7,'Roberto Carlo','Flores Gomez',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (8,'Emmanuel','Galvan Fontalba',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (9,'Carlos Javier','Garcia Escribano',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (10,'Eloy Rafael','Gonzalez Leon',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (11,'Fco Javier','Guerrero Molina',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (12,'Oscar','Heredia Tartajo',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (13,'Jaime','Herreria Jimenez',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (14,'Jesus','Lopez Gonzalez',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (15,'Daniel','Lozano Torrico',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (16,'Antonio','Luque Bravo',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (17,'Ulises','Luque Paez',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (18,'Rafael','Miranda Ibañez',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (19,'Javier','Moreno Alonso',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (20,'Raul','Moreno Povedano',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (21,'Estela','Muñoz Cordon',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (22,'Rafael','Navarro Prieto',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (23,'Elisa','Navarro Zuara',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (24,'Manuel','Ortega Peña',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (25,'David','Peralvo Gomez',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (26,'Pedro','Ramos Ruiz',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (27,'Miguel','Rodriguez Lopez',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (28,'Juan Antonio','Romero Molero',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (29,'Pablo','Sanchez Sanvicente',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (30,'Victoriano','Sevillano Vega',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (31,'Arturo','Urbano Gonzalez',1);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (32,'Miguel Angel','Zamora Blanco',1);

INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (33,'Juan Pedro','Adamuz Canales',2);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (34,'Daniel','Cabrera Cebrero',2);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (35,'Felipe','Cachinero Munor',2);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (36,'Carlos','Cordon Gomez',2);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (37,'Luis','Guirao Carmona',2);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (38,'Alejandro','Gutierrez Lozano',2);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (39,'Daniel','Gutierrez Lozano',2);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (40,'Juan Carlos','Herencia Castro',2);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (41,'Francisco''Herruzo Olmo',,2);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (42,'Antonio','Leon Alcaide',2);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (43,'Daniel','Lopez Marmol',2);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (44,'Antonio','Marmol Manchado',2);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (45,'Angel','Moreno Cubero',2);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (46,'Christopher','Muñoz Godenir',2);
INSERT INTO alumnos (idAlumnos,nombre,apellido,idGrupos) VALUES (47,'Maria de la Paz','Ruiz Garcia',2);
