var mensaje=["Enero",
			"Febrero",
			"Marzo",
			"Abril",
			"Mayo",
			"Junio",
			"Julio",
			"Agosto",
			"Septiembre",
			"Octubre",
			"Noviembre",
			"Diciembre"];
alert(mensaje[0]);
alert(mensaje[1]);
alert(mensaje[2]);
alert(mensaje[3]);
alert(mensaje[4]);
alert(mensaje[5]);
alert(mensaje[6]);
alert(mensaje[7]);
alert(mensaje[8]);
alert(mensaje[9]);
alert(mensaje[10]);
alert(mensaje[11]);